### ISSUE TITLE
Illegal string offset 'type'

### ISSUE THREAD

**Issue by bit-crafter** [MacGyer/yii2-cropit#3]
![image](https://user-images.githubusercontent.com/10452309/27517419-58f055d2-59dd-11e7-8d91-607976d6e9b6.png)

**Comment by MacGyer** [comment]
Can you please provide the widget call and the full stacktrace?

**Comment by bit-crafter** [comment]
I just try this example :(
```php
 $ <?= $form->field($model, 'cropped_image_data')->widget(\macgyer\yii2cropit\widgets\CropitWidget::className()) ?>
```

**Comment by MacGyer** [comment]
thanks. will look into it.

**Comment by MacGyer** [comment]
@tumdav Check release 1.0.3
